"""empty message

Revision ID: 9cad434bed4c
Revises: 
Create Date: 2025-01-07 11:54:55.569847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cad434bed4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landlords_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('issues', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('properties_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('llc', sa.String(), nullable=True),
    sa.Column('property_management', sa.String(), nullable=True),
    sa.Column('street_number', sa.Integer(), nullable=False),
    sa.Column('street_name', sa.String(), nullable=False),
    sa.Column('apartment_number', sa.Integer(), nullable=True),
    sa.Column('zip_code', sa.Integer(), nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords_table.id'], name=op.f('fk_properties_table_landlord_id_landlords_table')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('llc'),
    sa.UniqueConstraint('property_management')
    )
    op.create_table('ratings_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('landlord_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords_table.id'], name=op.f('fk_ratings_table_landlord_id_landlords_table')),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_ratings_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rating')
    )
    op.create_table('leases_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties_table.id'], name=op.f('fk_leases_table_property_id_properties_table')),
    sa.ForeignKeyConstraint(['user_id'], ['users_table.id'], name=op.f('fk_leases_table_user_id_users_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leases_table')
    op.drop_table('ratings_table')
    op.drop_table('properties_table')
    op.drop_table('users_table')
    op.drop_table('landlords_table')
    # ### end Alembic commands ###
